local robot = require("robot")

function placer()
	robot.down()
	robot.down()
	robot.placeDown()
	robot.up()
	robot.placeDown()
	robot.up()
	robot.placeDown()
end

function build()
	robot.select(1)
	placer()
	robot.forward()
	placer()
	robot.forward()
	placer()
	robot.turnRight()
	robot.forward()
	placer()
	robot.forward()
	placer()
	robot.turnRight()
	robot.forward()
	placer()
	robot.turnRight()
	robot.forward()
	robot.down()
	robot.down()
	robot.placeDown()
	robot.up()
	robot.select(2)
	robot.placeDown()
	robot.up()
	robot.select(1)
	robot.placeDown()
	robot.turnLeft()
	robot.forward()
	placer()
	robot.turnLeft()
	robot.forward()
	placer()
	robot.select(3)
	robot.turnRight()
	robot.forward()
	robot.forward()
	robot.turnAround()
	robot.drop(1)
	robot.select(1)
end

function positioning()
	robot.turnLeft()
	robot.forward()
	robot.forward()
	robot.forward()
	robot.turnLeft()
	robot.forward()
	robot.forward()
	robot.forward()
end

function returnhome()
	robot.back()
	robot.turnLeft()
	robot.forward()
	robot.forward()
	robot.forward()
	robot.forward()
	robot.forward()
	robot.turnLeft()
end

while true do
	robot.turnRight()
	robot.select(2)
	robot.suck(1)
	robot.turnRight()
	robot.select(1)
	robot.suck(robot.space(1))
	if robot.count(1)<26 then
		robot.suck(robot.space(1))
	end
	robot.turnRight()
	robot.select(3)
	robot.suck(1)
	robot.turnRight()
	if robot.count(1)>25 and robot.count(2)>0 and robot.count(3)>0 then
		robot.up()
		robot.up()
		robot.up()
		positioning()
		build()
		returnhome()
		robot.down()
		robot.down()
		robot.down()
		os.sleep(3)
	end
end
